name: Deploy

on: 
  push:
    branches:
      - never

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: npm i -g pnpm && pnpm install


      - name: Run test
        run: pnpm test

  migrate:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Env
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}" >> .env
          echo "REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}" >> .env

      - name: Install deps
        run: npm i -g pnpm && pnpm install

      - name: Migrate
        run: pnpm prisma migrate deploy

      # - name: Run seeds
      #   run: pnpm seed
  
  deploy:
    needs: [migrate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

            rm -rf template
            git clone https://github.com/idmaksim/template.git
            cd template

            openssl req -nodes -new -x509 -keyout private.key -out certificate.crt -days 365 -subj "/CN=domain.ru"

            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}" >> .env
            echo "REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}" >> .env 

            cat .env

            docker-compose down -v

            docker-compose up --build -d
  
